name: boxes
version: 0.1.0.0
synopsis: simple modules as records of functions
description: This project contains typeclasses to specify modules presenting interfaces.
             Interfaces are simple records of functions returning a `RIO` value where
             RIO is a Reader on top of IO.
             The test part shows how to define the modules, configure them, wire them,
             swap them. It also shows how to use contextual logging (pass a flow id
             or a logging context).
maintainer: etorreborre@yahoo.com
git: https://github.com/etorreborre/boxes

ghc-options: -Wall -fhide-source-paths -fprint-potential-instances

default-extensions:
 - OverloadedStrings
 - NoImplicitPrelude
 - LambdaCase

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - data-default
  - exceptions
  - hedgehog
  - microlens-th
  - protolude
  - resourcet
  - template-haskell
  - text
  - unliftio-core
  - unordered-containers
  - universum
  - uuid

library:
  source-dirs: src

tests:
  spec:
    main: test.hs
    source-dirs:
      - test
    dependencies:
      - hedgehog
      - hedgehog-corpus
      - lens
      - lens-aeson
      - boxes
      - monad-logger
      - tasty
      - tasty-discover
      - tasty-hedgehog
      - tasty-quickcheck
      - tasty-th
      - text
      - universum

    ghc-options: -threaded -rtsopts -with-rtsopts=-N -fno-warn-orphans -fno-warn-missing-signatures
