name: registry
version: 0.1.0.0
synopsis: the Registry data structure can be used for "dependency injection"
          but also to assemble JSON encoders/decoders or Hedgehog generators

description: This library provides a "Registry" data structure containing
             a list of functions representing values dependencies
             and a `make` function to create a specific value out of
             the registry

maintainer: etorreborre@yahoo.com
git: https://github.com/etorreborre/registry

ghc-options: -Wall -fhide-source-paths -fprint-potential-instances

default-extensions:
 - FlexibleContexts
 - FlexibleInstances
 - LambdaCase
 - MultiParamTypeClasses
 - NoImplicitPrelude
 - OverloadedStrings
 - Rank2Types
 - ScopedTypeVariables
 - ScopedTypeVariables
 - TupleSections
 - TypeApplications
 - TypeOperators

dependencies:
  - base >= 4.7 && < 5
  - exceptions
  - protolude
  - resourcet
  - text
  - transformers
  - transformers-base

library:
  source-dirs: src

tests:
  spec:
    main: test.hs
    source-dirs:
      - test
    dependencies:
      - async
      - hedgehog
      - hedgehog-corpus
      - registry
      - io-memoize
      - tasty
      - tasty-discover
      - tasty-hedgehog
      - tasty-th
      - text

    ghc-options: -threaded -rtsopts -with-rtsopts=-N -fno-warn-orphans -fno-warn-missing-signatures
