name: boxes
version: 0.1.0.0
synopsis: simple modules as records of functions
description: This project provides a "Registry" datatype containing
             a list of functions representing components dependencies
             and a `make` function to create a specific component out of
             the registry
maintainer: etorreborre@yahoo.com
git: https://github.com/etorreborre/boxes

ghc-options: -Wall -fhide-source-paths -fprint-potential-instances

default-extensions:
 - LambdaCase
 - NoImplicitPrelude
 - OverloadedStrings
 - ScopedTypeVariables

dependencies:
  - base >= 4.7 && < 5
  - protolude
  - text

library:
  source-dirs: src

tests:
  spec:
    main: test.hs
    source-dirs:
      - test
    dependencies:
      - hedgehog
      - boxes
      - io-memoize
      - tasty
      - tasty-discover
      - tasty-hedgehog
      - tasty-th
      - text

    ghc-options: -threaded -rtsopts -with-rtsopts=-N -fno-warn-orphans -fno-warn-missing-signatures
